### ISSUE TITLE
Support url params 

### ISSUE THREAD

**Issue by pglass** [pglbutt/noodles#50]
This may already work...

**Comment by Squab** [comment]
So this doesn't work exactly as you'd like. The `&` symbol obviously doesn't play nice with regular commands, as it backgrounds whatever it succeeds. But, much like having spaces in...well just about anything, it can be solved by putting the URI in quotes.

```python
@app.route('/params', methods=['GET'])
def params():
    return jsonify({key: value for key, value in request.args.items()})
```

One param works just fine.

```
$ spag get /params?foo=bar
{
  "foo": "bar"
}
```

Two, not so much.
```
$ spag get /params?foo=bar&bar=baz
[1] 30127
tim@timsim:~/code/noodles$ {
  "foo": "bar"
}

[1]+  Done                    ./target/debug/spag get /params?foo=bar
```

It works fine if you put the URI in quotes.
```
$ spag get '/params?foo=bar&bar=baz'
{
  "bar": "baz", 
  "foo": "bar"
}
```

Substitution works as well.
```
$ spag get '/params?foo=@[].bar&bar=@token'
{
  "bar": "abcde", 
  "foo": "butt"
}
```

I suppose we could add a mapping of extra `?`'s in a request and change them to `&`'s so that folks wouldn't have to quote the URIs, but that almost seems too confusing. Seems like a good general rule to just say "If the command line doesn't allow it, put it in quotes". 

If you have other ideas, or want to do do that ^ we can file an issue/feature for it, otherwise we can close this out, I think. I'll add a few unit tests for request params.
